spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      acks: all
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/assetDB
    username: admin
    password: password
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/assetsDB
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    operationsSorter: method
    tagsSorter: alpha
    filter: true
